### ISSUE TITLE
Authorising  Users  to Delete only own post

### ISSUE THREAD

**Issue by foliwe** [elorest/petergate#16]
Hello, I am trying to figure out how I can use this gem to give a user(devise) the ability to delete only his own posts. 
I will appreciate any help

**Comment by elorest** [comment]
My philosophy has always been to use default rails functionality here instead of reinventing the wheel.

````ruby
  def destroy
    current_user.posts.find(params[:id]).destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end
````

If you want different functionality for admins you could write something like this:

````ruby
  def destroy
    posts_scope.find(params[:id]).destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
  def posts_scope
    logged_in?(:admin) ? Post : current_user.posts
  end
````

**Comment by elorest** [comment]
@foliwe did that help?
