### ISSUE TITLE
Can't find generator 'petergate:install'

### ISSUE THREAD

**Issue by Cannonjc** [elorest/petergate#18]
Simply create a new rails app (5.1.2), install devise (4.3.0), install petergate, and can't get it to run install. 

Could not find generator 'petergate:install'. Maybe you meant 'devise:install', 'responders:install' or 'integration_test'

**Comment by elorest** [comment]
I just tested this with rails 5.1.2. Are you sure you ran bundle install after adding petergate to your Gemfile?

**Comment by elorest** [comment]
@Cannonjc Did that work?

**Comment by Cannonjc** [comment]
Thanks!
