### ISSUE TITLE
bundler cannot see i18n-0.8.6 when attempting to install petergate gem

### ISSUE THREAD

**Issue by ldco2016** [elorest/petergate#20]
What I tried to do

I tried to run
`rails g petergate:install`
What I expected to happen

I expected it to add a migration and insert petergate into my User model.

What actually happened

I got an error in terminal saying:
```

Could not find i18n-0.8.6 in any of the sources
Run `bundle install` to install missing gems.
```
I ran bundle install and retried rails g petergate:install, but the same error keeps occurring.
When I view my gems, I do have i18n-0.8.6

```
danales-MacBook-Pro:dancortesPortfolio danale$ rails g petergate:install
Could not find i18n-0.8.6 in any of the sources
Run `bundle install` to install missing gems.
danales-MacBook-Pro:dancortesPortfolio danale$ bundle install
Using rake 12.0.0
Using concurrent-ruby 1.0.5
Using i18n 0.8.6
```

**Comment by ldco2016** [comment]
I remembered I had did an rvm 2.4 to create a new ruby gem last night. I switched back to 2.3.3 and rails g petergate:install works!

**Comment by elorest** [comment]
Interesting. Could you describe your setup to me? Is this in a rails
project? Is petergate in your gemfile?

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005

**Comment by ldco2016** [comment]
Hi Isaac,

Thank you for responding to me. I have heard positive things about you. I was following your Github guide for installing the petergate gem to my application. I am on a MacBook Pro. I kept getting an error at the point where I had to do the rails g petergate:install saying that it could not find the gem i18n-0.8.6 but that dependency gem was definitely in my Gemfile.lock.

After another developer asked to see my ruby -v, I remember that last night I did an rvm 2.4 to work on developing a new gem and I did not switch it back to rvm 2.3.3. After having done that, I was able to install petergate successfully.

**Comment by elorest** [comment]
I'll look into why it doesn't work with ruby 2.4. How did you hear about petergate?

**Comment by ldco2016** [comment]
From Jordan Hudgens, he says he knows you personally, he was speaking highly of you so I decided to look you up and implement petergate into my future portfolios website for authorization purposes. In other words to create roles between admin users and regular users.
