### ISSUE TITLE
Undefined method `access' when using ActionController::API

### ISSUE THREAD

**Issue by Badmuts** [elorest/petergate#24]
Hi there!

First of all I am new to Ruby and Ruby on Rails. Via the Udemy course: Dissecting Ruby on Rails 5 I ran into this library.

Currently I am building an REST API and would like to use Petergate for Authorization (Authentication via knock) but ran into a problem.

I generated an new rails app with the `--api` flag. When you do this Rails creates an `ApplicationController` that extends from `ActionController::API` and here is where the problem lies. When you then try to use the `access` method you get the following error:

```
ActionController::RoutingError (undefined method `access' for UsersController:Class):
```

Is this expected behaviour? When I change the `ApplicationContoller` to extend from `ActionController::Base` everything works fine.

**Comment by elorest** [comment]
Yeah that makes sense. Most of my apps are still mixed web and api, so I
haven't had this issue. Check if there's a parent of both ActionController::API
and ActionController::Base that petergate could add access onto instead.

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005

**Comment by Badmuts** [comment]
Thanks for the fast reply! I found out that by including `Petergate::ActionController::Base` and `ActionController::Helpers` into the `ApplicationController` everything is working.

`application_controller.rb`:
```ruby
class ApplicationController < ActionController::API
  include Knock::Authenticable, Petergate::ActionController::Base, ActionController::Helpers
end
```

(Knock is not necessary, its the authentication library that I use)

I don't really know how to contribute a solution so that Petergate will also work with ActionController::API but for now this issue can be closed.

**Comment by elorest** [comment]
Ok. Well thanks for reporting that.
