### ISSUE TITLE
Unauthenticated user role

### ISSUE THREAD

**Issue by Uzval-Mallepeddi** [elorest/petergate#37]
Imagine a testcase where a specific controller has access privileges for its actions.
Let's say there's a controller "Test" and it has actions like "show", "new", "create" and i created an access privilege using petergate for different roles.
_access user: [show], admin: [new create]_
The test case that's bugging me is that what if the user is NOT AUTHENTICATED and want to access a page of this "Test" controller ??
I tried to create a replica of "Test" contoller, create new views for it and on form submission, i tried to push the form data into the "Test" model. But it's not allowing me to do so as Test controller is linked to Test model.

Need help on this !

**Comment by elorest** [comment]
Use `access all: [yourpage]`

**Comment by Uzval-Mallepeddi** [comment]
> Use `access all: [yourpage]`

If i use access all:, user will be able to access the pages he shouldn't.

**Comment by elorest** [comment]
Maybe I don't fully understand what you're trying to do.

`access all: [:index], user: [:show], admin: :all`

user can access anything a none user can and admin can access anything a plain user can. Because an `admin` is a `user` and a `user` is contained in the concept of `all`.
